"""Generate the synchronous Flutter catalog from the authoring source of truth."""
import argparse, copy, json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
source = json.loads((Path(__file__).parent / 'catalog.json').read_text())
assert source['schemaVersion'] == 1
parser = argparse.ArgumentParser()
parser.add_argument('--review-candidates', default='', help='Temporary QA catalog; restore with a normal generation after testing')
args = parser.parse_args()
candidates = set(filter(None, args.review_candidates.split(',')))
ids, names = set(), set()
for item in source['exercises']:
    assert item['exerciseId'] not in ids
    ids.add(item['exerciseId'])
    for name in [item['exerciseName'], *item['aliases']]:
        assert name not in names, name
        names.add(name)
    assert 0 < item['animationSpeed'] <= 2
    assert 0 < item['rangeOfMotion'] <= 1
    assert item['status'] in ['planned', 'authored', 'verified']
    if item['status'] == 'verified':
        assert item['assetPath'] and (ROOT / item['assetPath']).is_file()
        if item['exerciseId'] not in {'bench_press', 'incline_dumbbell_press'}:
            assert item.get('references'), f'Missing reference: {item["exerciseId"]}'
            for check in ('equipmentReference', 'staticPose', 'motion', 'android', 'ios', 'productionRoute'):
                assert item.get('review', {}).get(check) is True, f'Unreviewed {check}: {item["exerciseId"]}'
assert candidates <= ids, f'Unknown QA candidates: {candidates - ids}'
output = copy.deepcopy(source['exercises'])
for item in output:
    if item['exerciseId'] in candidates:
        assert item['status'] == 'authored' and item['assetPath']
        for check in ('equipmentReference', 'staticPose', 'motion', 'android', 'ios'):
            assert item.get('review', {}).get(check) is True, f'Unreviewed candidate {check}: {item["exerciseId"]}'
        item['status'] = 'verified'
text = '// GENERATED by tool/exercise_forms/generate_catalog.py. Edit catalog.json.\n'
if candidates:
    text += '// TEMPORARY QA CANDIDATES: ' + ','.join(sorted(candidates)) + '. Regenerate before release.\n'
text += 'const List<Map<String, Object?>> exerciseFormData = '
text += json.dumps(output, ensure_ascii=False, indent=2) + ';\n'
(ROOT / 'lib/exercise_form_catalog.g.dart').write_text(text)
print(f'Generated {len(ids)} definitions')
