-- Multi-equipment exercise availability for gym store filtering.
begin;

create table if not exists public.exercise_equipment_rules (
  id text primary key,
  exercise_id text not null check(length(exercise_id) > 0),
  rationale text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.exercise_equipment_rule_items (
  rule_id text not null references public.exercise_equipment_rules(id) on delete cascade,
  equipment_id text not null references public.equipment(id) on delete cascade,
  primary key(rule_id, equipment_id)
);

create index if not exists exercise_equipment_rules_exercise_idx
  on public.exercise_equipment_rules(exercise_id);
create index if not exists exercise_equipment_rule_items_equipment_idx
  on public.exercise_equipment_rule_items(equipment_id);

alter table public.exercise_equipment_rules enable row level security;
alter table public.exercise_equipment_rule_items enable row level security;

revoke all on public.exercise_equipment_rules, public.exercise_equipment_rule_items
  from anon, authenticated;
grant select on public.exercise_equipment_rules, public.exercise_equipment_rule_items
  to anon, authenticated;

drop policy if exists exercise_equipment_rules_read on public.exercise_equipment_rules;
create policy exercise_equipment_rules_read on public.exercise_equipment_rules
  for select to anon, authenticated using (true);

drop policy if exists exercise_equipment_rule_items_read on public.exercise_equipment_rule_items;
create policy exercise_equipment_rule_items_read on public.exercise_equipment_rule_items
  for select to anon, authenticated using (true);

-- Generic curl benches do not prove that a free-weight preacher curl is possible
-- on their own. They are handled below as dumbbell/rack + curl-bench combinations.
delete from public.equipment_exercise_mapping
where exercise_id = 'preacher_curl'
  and equipment_id in (
    'fit-place24:fp_eq_999e7b88bccd',
    'fit-place24:fp_eq_5354722256ab',
    'fit-place24:fp_eq_53beebd50e63'
  );

insert into public.equipment_exercise_mapping (equipment_id, exercise_id, rationale)
values
  ('fit-place24:fp_eq_d45213d7da37', 'barbell_squat', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_d45213d7da37', 'front_squat', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_d45213d7da37', 'rack_pull', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_d45213d7da37', 'good_morning', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_d45213d7da37', 'military_press', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_d45213d7da37', 'bent_over_row', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_d45213d7da37', 'pendlay_row', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_d45213d7da37', 'deadlift', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_d45213d7da37', 'romanian_deadlift', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_d45213d7da37', 'sumo_deadlift', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_d45213d7da37', 'barbell_curl', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_d45213d7da37', 'upright_row', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_d45213d7da37', 'barbell_shrug', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_0b00220775cb', 'barbell_squat', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_0b00220775cb', 'front_squat', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_0b00220775cb', 'rack_pull', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_0b00220775cb', 'good_morning', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_0b00220775cb', 'military_press', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_0b00220775cb', 'bent_over_row', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_0b00220775cb', 'pendlay_row', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_0b00220775cb', 'deadlift', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_0b00220775cb', 'romanian_deadlift', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_0b00220775cb', 'sumo_deadlift', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_0b00220775cb', 'barbell_curl', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_0b00220775cb', 'upright_row', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_0b00220775cb', 'barbell_shrug', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_0287f92794a6', 'barbell_squat', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_0287f92794a6', 'front_squat', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_0287f92794a6', 'rack_pull', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_0287f92794a6', 'good_morning', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_0287f92794a6', 'military_press', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_0287f92794a6', 'bent_over_row', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_0287f92794a6', 'pendlay_row', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_0287f92794a6', 'deadlift', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_0287f92794a6', 'romanian_deadlift', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_0287f92794a6', 'sumo_deadlift', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_0287f92794a6', 'barbell_curl', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_0287f92794a6', 'upright_row', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_0287f92794a6', 'barbell_shrug', 'ラック設備をバーベル系フリーウェイト種目の起点として扱う。ベンチが必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_693fa2dd0404', 'dumbbell_curl', 'ダンベル単体で実施できる種目として紐付け。ベンチ等が必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_693fa2dd0404', 'hammer_curl', 'ダンベル単体で実施できる種目として紐付け。ベンチ等が必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_693fa2dd0404', 'lateral_raise', 'ダンベル単体で実施できる種目として紐付け。ベンチ等が必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_693fa2dd0404', 'front_raise', 'ダンベル単体で実施できる種目として紐付け。ベンチ等が必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_693fa2dd0404', 'one_arm_dumbbell_row', 'ダンベル単体で実施できる種目として紐付け。ベンチ等が必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_693fa2dd0404', 'goblet_squat', 'ダンベル単体で実施できる種目として紐付け。ベンチ等が必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_693fa2dd0404', 'dumbbell_shoulder_press', 'ダンベル単体で実施できる種目として紐付け。ベンチ等が必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_693fa2dd0404', 'rear_raise', 'ダンベル単体で実施できる種目として紐付け。ベンチ等が必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_693fa2dd0404', 'dumbbell_shrug', 'ダンベル単体で実施できる種目として紐付け。ベンチ等が必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_693fa2dd0404', 'concentration_curl', 'ダンベル単体で実施できる種目として紐付け。ベンチ等が必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_693fa2dd0404', 'zottman_curl', 'ダンベル単体で実施できる種目として紐付け。ベンチ等が必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_693fa2dd0404', 'french_press', 'ダンベル単体で実施できる種目として紐付け。ベンチ等が必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_693fa2dd0404', 'triceps_kickback', 'ダンベル単体で実施できる種目として紐付け。ベンチ等が必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_693fa2dd0404', 'lunge', 'ダンベル単体で実施できる種目として紐付け。ベンチ等が必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_693fa2dd0404', 'reverse_lunge', 'ダンベル単体で実施できる種目として紐付け。ベンチ等が必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_693fa2dd0404', 'walking_lunge', 'ダンベル単体で実施できる種目として紐付け。ベンチ等が必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_693fa2dd0404', 'split_squat', 'ダンベル単体で実施できる種目として紐付け。ベンチ等が必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_693fa2dd0404', 'single_leg_rdl', 'ダンベル単体で実施できる種目として紐付け。ベンチ等が必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_693fa2dd0404', 'weighted_crunch', 'ダンベル単体で実施できる種目として紐付け。ベンチ等が必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_693fa2dd0404', 'russian_twist', 'ダンベル単体で実施できる種目として紐付け。ベンチ等が必要な種目は別の複数設備ルールで判定する。'),
  ('fit-place24:fp_eq_693fa2dd0404', 'arnold_press', 'ダンベル単体で実施できる種目として紐付け。ベンチ等が必要な種目は別の複数設備ルールで判定する。')
on conflict (equipment_id, exercise_id)
do update set rationale = excluded.rationale;

insert into public.exercise_equipment_rules (id, exercise_id, rationale)
values
  ('rack_flat_bench_press_half_adj_incline', 'bench_press', 'bench_press は half と adj_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_bench_press_half_flat_incline', 'bench_press', 'bench_press は half と flat_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_bench_press_half_adjustable', 'bench_press', 'bench_press は half と adjustable の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_bench_press_half_multi_decline', 'bench_press', 'bench_press は half と multi_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_bench_press_half_multi_adj_decline', 'bench_press', 'bench_press は half と multi_adj_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_bench_press_half_decline_flat', 'bench_press', 'bench_press は half と decline_flat の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_bench_press_half_flat', 'bench_press', 'bench_press は half と flat の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_bench_press_power_adj_incline', 'bench_press', 'bench_press は power と adj_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_bench_press_power_flat_incline', 'bench_press', 'bench_press は power と flat_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_bench_press_power_adjustable', 'bench_press', 'bench_press は power と adjustable の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_bench_press_power_multi_decline', 'bench_press', 'bench_press は power と multi_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_bench_press_power_multi_adj_decline', 'bench_press', 'bench_press は power と multi_adj_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_bench_press_power_decline_flat', 'bench_press', 'bench_press は power と decline_flat の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_bench_press_power_flat', 'bench_press', 'bench_press は power と flat の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_bench_press_multi_adj_incline', 'bench_press', 'bench_press は multi と adj_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_bench_press_multi_flat_incline', 'bench_press', 'bench_press は multi と flat_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_bench_press_multi_adjustable', 'bench_press', 'bench_press は multi と adjustable の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_bench_press_multi_multi_decline', 'bench_press', 'bench_press は multi と multi_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_bench_press_multi_multi_adj_decline', 'bench_press', 'bench_press は multi と multi_adj_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_bench_press_multi_decline_flat', 'bench_press', 'bench_press は multi と decline_flat の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_bench_press_multi_flat', 'bench_press', 'bench_press は multi と flat の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_close_grip_bench_press_half_adj_incline', 'close_grip_bench_press', 'close_grip_bench_press は half と adj_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_close_grip_bench_press_half_flat_incline', 'close_grip_bench_press', 'close_grip_bench_press は half と flat_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_close_grip_bench_press_half_adjustable', 'close_grip_bench_press', 'close_grip_bench_press は half と adjustable の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_close_grip_bench_press_half_multi_decline', 'close_grip_bench_press', 'close_grip_bench_press は half と multi_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_close_grip_bench_press_half_multi_adj_decline', 'close_grip_bench_press', 'close_grip_bench_press は half と multi_adj_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_close_grip_bench_press_half_decline_flat', 'close_grip_bench_press', 'close_grip_bench_press は half と decline_flat の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_close_grip_bench_press_half_flat', 'close_grip_bench_press', 'close_grip_bench_press は half と flat の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_close_grip_bench_press_power_adj_incline', 'close_grip_bench_press', 'close_grip_bench_press は power と adj_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_close_grip_bench_press_power_flat_incline', 'close_grip_bench_press', 'close_grip_bench_press は power と flat_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_close_grip_bench_press_power_adjustable', 'close_grip_bench_press', 'close_grip_bench_press は power と adjustable の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_close_grip_bench_press_power_multi_decline', 'close_grip_bench_press', 'close_grip_bench_press は power と multi_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_close_grip_bench_press_power_multi_adj_decline', 'close_grip_bench_press', 'close_grip_bench_press は power と multi_adj_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_close_grip_bench_press_power_decline_flat', 'close_grip_bench_press', 'close_grip_bench_press は power と decline_flat の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_close_grip_bench_press_power_flat', 'close_grip_bench_press', 'close_grip_bench_press は power と flat の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_close_grip_bench_press_multi_adj_incline', 'close_grip_bench_press', 'close_grip_bench_press は multi と adj_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_close_grip_bench_press_multi_flat_incline', 'close_grip_bench_press', 'close_grip_bench_press は multi と flat_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_close_grip_bench_press_multi_adjustable', 'close_grip_bench_press', 'close_grip_bench_press は multi と adjustable の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_close_grip_bench_press_multi_multi_decline', 'close_grip_bench_press', 'close_grip_bench_press は multi と multi_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_close_grip_bench_press_multi_multi_adj_decline', 'close_grip_bench_press', 'close_grip_bench_press は multi と multi_adj_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_close_grip_bench_press_multi_decline_flat', 'close_grip_bench_press', 'close_grip_bench_press は multi と decline_flat の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_close_grip_bench_press_multi_flat', 'close_grip_bench_press', 'close_grip_bench_press は multi と flat の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_skull_crusher_half_adj_incline', 'skull_crusher', 'skull_crusher は half と adj_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_skull_crusher_half_flat_incline', 'skull_crusher', 'skull_crusher は half と flat_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_skull_crusher_half_adjustable', 'skull_crusher', 'skull_crusher は half と adjustable の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_skull_crusher_half_multi_decline', 'skull_crusher', 'skull_crusher は half と multi_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_skull_crusher_half_multi_adj_decline', 'skull_crusher', 'skull_crusher は half と multi_adj_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_skull_crusher_half_decline_flat', 'skull_crusher', 'skull_crusher は half と decline_flat の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_skull_crusher_half_flat', 'skull_crusher', 'skull_crusher は half と flat の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_skull_crusher_power_adj_incline', 'skull_crusher', 'skull_crusher は power と adj_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_skull_crusher_power_flat_incline', 'skull_crusher', 'skull_crusher は power と flat_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_skull_crusher_power_adjustable', 'skull_crusher', 'skull_crusher は power と adjustable の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_skull_crusher_power_multi_decline', 'skull_crusher', 'skull_crusher は power と multi_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_skull_crusher_power_multi_adj_decline', 'skull_crusher', 'skull_crusher は power と multi_adj_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_skull_crusher_power_decline_flat', 'skull_crusher', 'skull_crusher は power と decline_flat の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_skull_crusher_power_flat', 'skull_crusher', 'skull_crusher は power と flat の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_skull_crusher_multi_adj_incline', 'skull_crusher', 'skull_crusher は multi と adj_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_skull_crusher_multi_flat_incline', 'skull_crusher', 'skull_crusher は multi と flat_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_skull_crusher_multi_adjustable', 'skull_crusher', 'skull_crusher は multi と adjustable の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_skull_crusher_multi_multi_decline', 'skull_crusher', 'skull_crusher は multi と multi_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_skull_crusher_multi_multi_adj_decline', 'skull_crusher', 'skull_crusher は multi と multi_adj_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_skull_crusher_multi_decline_flat', 'skull_crusher', 'skull_crusher は multi と decline_flat の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_skull_crusher_multi_flat', 'skull_crusher', 'skull_crusher は multi と flat の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_hip_thrust_half_adj_incline', 'hip_thrust', 'hip_thrust は half と adj_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_hip_thrust_half_flat_incline', 'hip_thrust', 'hip_thrust は half と flat_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_hip_thrust_half_adjustable', 'hip_thrust', 'hip_thrust は half と adjustable の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_hip_thrust_half_multi_decline', 'hip_thrust', 'hip_thrust は half と multi_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_hip_thrust_half_multi_adj_decline', 'hip_thrust', 'hip_thrust は half と multi_adj_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_hip_thrust_half_decline_flat', 'hip_thrust', 'hip_thrust は half と decline_flat の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_hip_thrust_half_flat', 'hip_thrust', 'hip_thrust は half と flat の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_hip_thrust_power_adj_incline', 'hip_thrust', 'hip_thrust は power と adj_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_hip_thrust_power_flat_incline', 'hip_thrust', 'hip_thrust は power と flat_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_hip_thrust_power_adjustable', 'hip_thrust', 'hip_thrust は power と adjustable の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_hip_thrust_power_multi_decline', 'hip_thrust', 'hip_thrust は power と multi_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_hip_thrust_power_multi_adj_decline', 'hip_thrust', 'hip_thrust は power と multi_adj_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_hip_thrust_power_decline_flat', 'hip_thrust', 'hip_thrust は power と decline_flat の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_hip_thrust_power_flat', 'hip_thrust', 'hip_thrust は power と flat の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_hip_thrust_multi_adj_incline', 'hip_thrust', 'hip_thrust は multi と adj_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_hip_thrust_multi_flat_incline', 'hip_thrust', 'hip_thrust は multi と flat_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_hip_thrust_multi_adjustable', 'hip_thrust', 'hip_thrust は multi と adjustable の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_hip_thrust_multi_multi_decline', 'hip_thrust', 'hip_thrust は multi と multi_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_hip_thrust_multi_multi_adj_decline', 'hip_thrust', 'hip_thrust は multi と multi_adj_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_hip_thrust_multi_decline_flat', 'hip_thrust', 'hip_thrust は multi と decline_flat の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_flat_hip_thrust_multi_flat', 'hip_thrust', 'hip_thrust は multi と flat の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_incline_incline_barbell_press_half_adj_incline', 'incline_barbell_press', 'incline_barbell_press は half と adj_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_incline_incline_barbell_press_half_flat_incline', 'incline_barbell_press', 'incline_barbell_press は half と flat_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_incline_incline_barbell_press_half_adjustable', 'incline_barbell_press', 'incline_barbell_press は half と adjustable の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_incline_incline_barbell_press_power_adj_incline', 'incline_barbell_press', 'incline_barbell_press は power と adj_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_incline_incline_barbell_press_power_flat_incline', 'incline_barbell_press', 'incline_barbell_press は power と flat_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_incline_incline_barbell_press_power_adjustable', 'incline_barbell_press', 'incline_barbell_press は power と adjustable の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_incline_incline_barbell_press_multi_adj_incline', 'incline_barbell_press', 'incline_barbell_press は multi と adj_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_incline_incline_barbell_press_multi_flat_incline', 'incline_barbell_press', 'incline_barbell_press は multi と flat_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_incline_incline_barbell_press_multi_adjustable', 'incline_barbell_press', 'incline_barbell_press は multi と adjustable の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_decline_decline_barbell_press_half_multi_decline', 'decline_barbell_press', 'decline_barbell_press は half と multi_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_decline_decline_barbell_press_half_multi_adj_decline', 'decline_barbell_press', 'decline_barbell_press は half と multi_adj_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_decline_decline_barbell_press_half_decline_flat', 'decline_barbell_press', 'decline_barbell_press は half と decline_flat の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_decline_decline_barbell_press_power_multi_decline', 'decline_barbell_press', 'decline_barbell_press は power と multi_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_decline_decline_barbell_press_power_multi_adj_decline', 'decline_barbell_press', 'decline_barbell_press は power と multi_adj_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_decline_decline_barbell_press_power_decline_flat', 'decline_barbell_press', 'decline_barbell_press は power と decline_flat の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_decline_decline_barbell_press_multi_multi_decline', 'decline_barbell_press', 'decline_barbell_press は multi と multi_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_decline_decline_barbell_press_multi_multi_adj_decline', 'decline_barbell_press', 'decline_barbell_press は multi と multi_adj_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('rack_decline_decline_barbell_press_multi_decline_flat', 'decline_barbell_press', 'decline_barbell_press は multi と decline_flat の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_flat_flat_dumbbell_press_db_adj_incline', 'flat_dumbbell_press', 'flat_dumbbell_press は db と adj_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_flat_flat_dumbbell_press_db_flat_incline', 'flat_dumbbell_press', 'flat_dumbbell_press は db と flat_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_flat_flat_dumbbell_press_db_adjustable', 'flat_dumbbell_press', 'flat_dumbbell_press は db と adjustable の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_flat_flat_dumbbell_press_db_multi_decline', 'flat_dumbbell_press', 'flat_dumbbell_press は db と multi_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_flat_flat_dumbbell_press_db_multi_adj_decline', 'flat_dumbbell_press', 'flat_dumbbell_press は db と multi_adj_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_flat_flat_dumbbell_press_db_decline_flat', 'flat_dumbbell_press', 'flat_dumbbell_press は db と decline_flat の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_flat_flat_dumbbell_press_db_flat', 'flat_dumbbell_press', 'flat_dumbbell_press は db と flat の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_flat_dumbbell_fly_db_adj_incline', 'dumbbell_fly', 'dumbbell_fly は db と adj_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_flat_dumbbell_fly_db_flat_incline', 'dumbbell_fly', 'dumbbell_fly は db と flat_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_flat_dumbbell_fly_db_adjustable', 'dumbbell_fly', 'dumbbell_fly は db と adjustable の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_flat_dumbbell_fly_db_multi_decline', 'dumbbell_fly', 'dumbbell_fly は db と multi_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_flat_dumbbell_fly_db_multi_adj_decline', 'dumbbell_fly', 'dumbbell_fly は db と multi_adj_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_flat_dumbbell_fly_db_decline_flat', 'dumbbell_fly', 'dumbbell_fly は db と decline_flat の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_flat_dumbbell_fly_db_flat', 'dumbbell_fly', 'dumbbell_fly は db と flat の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_flat_dumbbell_pullover_db_adj_incline', 'dumbbell_pullover', 'dumbbell_pullover は db と adj_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_flat_dumbbell_pullover_db_flat_incline', 'dumbbell_pullover', 'dumbbell_pullover は db と flat_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_flat_dumbbell_pullover_db_adjustable', 'dumbbell_pullover', 'dumbbell_pullover は db と adjustable の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_flat_dumbbell_pullover_db_multi_decline', 'dumbbell_pullover', 'dumbbell_pullover は db と multi_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_flat_dumbbell_pullover_db_multi_adj_decline', 'dumbbell_pullover', 'dumbbell_pullover は db と multi_adj_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_flat_dumbbell_pullover_db_decline_flat', 'dumbbell_pullover', 'dumbbell_pullover は db と decline_flat の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_flat_dumbbell_pullover_db_flat', 'dumbbell_pullover', 'dumbbell_pullover は db と flat の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_flat_bulgarian_split_squat_db_adj_incline', 'bulgarian_split_squat', 'bulgarian_split_squat は db と adj_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_flat_bulgarian_split_squat_db_flat_incline', 'bulgarian_split_squat', 'bulgarian_split_squat は db と flat_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_flat_bulgarian_split_squat_db_adjustable', 'bulgarian_split_squat', 'bulgarian_split_squat は db と adjustable の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_flat_bulgarian_split_squat_db_multi_decline', 'bulgarian_split_squat', 'bulgarian_split_squat は db と multi_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_flat_bulgarian_split_squat_db_multi_adj_decline', 'bulgarian_split_squat', 'bulgarian_split_squat は db と multi_adj_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_flat_bulgarian_split_squat_db_decline_flat', 'bulgarian_split_squat', 'bulgarian_split_squat は db と decline_flat の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_flat_bulgarian_split_squat_db_flat', 'bulgarian_split_squat', 'bulgarian_split_squat は db と flat の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_incline_incline_dumbbell_press_db_adj_incline', 'incline_dumbbell_press', 'incline_dumbbell_press は db と adj_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_incline_incline_dumbbell_press_db_flat_incline', 'incline_dumbbell_press', 'incline_dumbbell_press は db と flat_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_incline_incline_dumbbell_press_db_adjustable', 'incline_dumbbell_press', 'incline_dumbbell_press は db と adjustable の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_incline_incline_dumbbell_fly_db_adj_incline', 'incline_dumbbell_fly', 'incline_dumbbell_fly は db と adj_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_incline_incline_dumbbell_fly_db_flat_incline', 'incline_dumbbell_fly', 'incline_dumbbell_fly は db と flat_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_incline_incline_dumbbell_fly_db_adjustable', 'incline_dumbbell_fly', 'incline_dumbbell_fly は db と adjustable の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_incline_chest_supported_dumbbell_row_db_adj_incline', 'chest_supported_dumbbell_row', 'chest_supported_dumbbell_row は db と adj_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_incline_chest_supported_dumbbell_row_db_flat_incline', 'chest_supported_dumbbell_row', 'chest_supported_dumbbell_row は db と flat_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_incline_chest_supported_dumbbell_row_db_adjustable', 'chest_supported_dumbbell_row', 'chest_supported_dumbbell_row は db と adjustable の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_incline_incline_dumbbell_curl_db_adj_incline', 'incline_dumbbell_curl', 'incline_dumbbell_curl は db と adj_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_incline_incline_dumbbell_curl_db_flat_incline', 'incline_dumbbell_curl', 'incline_dumbbell_curl は db と flat_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_incline_incline_dumbbell_curl_db_adjustable', 'incline_dumbbell_curl', 'incline_dumbbell_curl は db と adjustable の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_incline_spider_curl_db_adj_incline', 'spider_curl', 'spider_curl は db と adj_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_incline_spider_curl_db_flat_incline', 'spider_curl', 'spider_curl は db と flat_incline の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_incline_spider_curl_db_adjustable', 'spider_curl', 'spider_curl は db と adjustable の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_decline_decline_dumbbell_press_db_multi_decline', 'decline_dumbbell_press', 'decline_dumbbell_press は db と multi_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_decline_decline_dumbbell_press_db_multi_adj_decline', 'decline_dumbbell_press', 'decline_dumbbell_press は db と multi_adj_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_decline_decline_dumbbell_press_db_decline_flat', 'decline_dumbbell_press', 'decline_dumbbell_press は db と decline_flat の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_decline_decline_dumbbell_fly_db_multi_decline', 'decline_dumbbell_fly', 'decline_dumbbell_fly は db と multi_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_decline_decline_dumbbell_fly_db_multi_adj_decline', 'decline_dumbbell_fly', 'decline_dumbbell_fly は db と multi_adj_decline の両設備がある場合のみ店舗対応と判定する。'),
  ('dumbbell_decline_decline_dumbbell_fly_db_decline_flat', 'decline_dumbbell_fly', 'decline_dumbbell_fly は db と decline_flat の両設備がある場合のみ店舗対応と判定する。'),
  ('preacher_db_preacher_curl_db_adj_arm', 'preacher_curl', 'preacher_curl は db と adj_arm の両設備がある場合のみ店舗対応と判定する。'),
  ('preacher_db_preacher_curl_db_arm', 'preacher_curl', 'preacher_curl は db と arm の両設備がある場合のみ店舗対応と判定する。'),
  ('preacher_db_preacher_curl_db_curl', 'preacher_curl', 'preacher_curl は db と curl の両設備がある場合のみ店舗対応と判定する。'),
  ('preacher_rack_preacher_curl_half_adj_arm', 'preacher_curl', 'preacher_curl は half と adj_arm の両設備がある場合のみ店舗対応と判定する。'),
  ('preacher_rack_preacher_curl_half_arm', 'preacher_curl', 'preacher_curl は half と arm の両設備がある場合のみ店舗対応と判定する。'),
  ('preacher_rack_preacher_curl_half_curl', 'preacher_curl', 'preacher_curl は half と curl の両設備がある場合のみ店舗対応と判定する。'),
  ('preacher_rack_preacher_curl_power_adj_arm', 'preacher_curl', 'preacher_curl は power と adj_arm の両設備がある場合のみ店舗対応と判定する。'),
  ('preacher_rack_preacher_curl_power_arm', 'preacher_curl', 'preacher_curl は power と arm の両設備がある場合のみ店舗対応と判定する。'),
  ('preacher_rack_preacher_curl_power_curl', 'preacher_curl', 'preacher_curl は power と curl の両設備がある場合のみ店舗対応と判定する。'),
  ('preacher_rack_preacher_curl_multi_adj_arm', 'preacher_curl', 'preacher_curl は multi と adj_arm の両設備がある場合のみ店舗対応と判定する。'),
  ('preacher_rack_preacher_curl_multi_arm', 'preacher_curl', 'preacher_curl は multi と arm の両設備がある場合のみ店舗対応と判定する。'),
  ('preacher_rack_preacher_curl_multi_curl', 'preacher_curl', 'preacher_curl は multi と curl の両設備がある場合のみ店舗対応と判定する。')
on conflict (id)
do update set
  exercise_id = excluded.exercise_id,
  rationale = excluded.rationale,
  updated_at = now();

insert into public.exercise_equipment_rule_items (rule_id, equipment_id)
values
  ('rack_flat_bench_press_half_adj_incline', 'fit-place24:fp_eq_d45213d7da37'),
  ('rack_flat_bench_press_half_adj_incline', 'fit-place24:fp_eq_0b7ade05c9c0'),
  ('rack_flat_bench_press_half_flat_incline', 'fit-place24:fp_eq_d45213d7da37'),
  ('rack_flat_bench_press_half_flat_incline', 'fit-place24:fp_eq_f03fe62567c5'),
  ('rack_flat_bench_press_half_adjustable', 'fit-place24:fp_eq_d45213d7da37'),
  ('rack_flat_bench_press_half_adjustable', 'fit-place24:fp_eq_c66a841e9ed5'),
  ('rack_flat_bench_press_half_multi_decline', 'fit-place24:fp_eq_d45213d7da37'),
  ('rack_flat_bench_press_half_multi_decline', 'fit-place24:fp_eq_538b557739d4'),
  ('rack_flat_bench_press_half_multi_adj_decline', 'fit-place24:fp_eq_d45213d7da37'),
  ('rack_flat_bench_press_half_multi_adj_decline', 'fit-place24:fp_eq_453fcb2d0cc8'),
  ('rack_flat_bench_press_half_decline_flat', 'fit-place24:fp_eq_d45213d7da37'),
  ('rack_flat_bench_press_half_decline_flat', 'fit-place24:fp_eq_57ab45d08062'),
  ('rack_flat_bench_press_half_flat', 'fit-place24:fp_eq_d45213d7da37'),
  ('rack_flat_bench_press_half_flat', 'fit-place24:fp_eq_3e928d59ac6c'),
  ('rack_flat_bench_press_power_adj_incline', 'fit-place24:fp_eq_0b00220775cb'),
  ('rack_flat_bench_press_power_adj_incline', 'fit-place24:fp_eq_0b7ade05c9c0'),
  ('rack_flat_bench_press_power_flat_incline', 'fit-place24:fp_eq_0b00220775cb'),
  ('rack_flat_bench_press_power_flat_incline', 'fit-place24:fp_eq_f03fe62567c5'),
  ('rack_flat_bench_press_power_adjustable', 'fit-place24:fp_eq_0b00220775cb'),
  ('rack_flat_bench_press_power_adjustable', 'fit-place24:fp_eq_c66a841e9ed5'),
  ('rack_flat_bench_press_power_multi_decline', 'fit-place24:fp_eq_0b00220775cb'),
  ('rack_flat_bench_press_power_multi_decline', 'fit-place24:fp_eq_538b557739d4'),
  ('rack_flat_bench_press_power_multi_adj_decline', 'fit-place24:fp_eq_0b00220775cb'),
  ('rack_flat_bench_press_power_multi_adj_decline', 'fit-place24:fp_eq_453fcb2d0cc8'),
  ('rack_flat_bench_press_power_decline_flat', 'fit-place24:fp_eq_0b00220775cb'),
  ('rack_flat_bench_press_power_decline_flat', 'fit-place24:fp_eq_57ab45d08062'),
  ('rack_flat_bench_press_power_flat', 'fit-place24:fp_eq_0b00220775cb'),
  ('rack_flat_bench_press_power_flat', 'fit-place24:fp_eq_3e928d59ac6c'),
  ('rack_flat_bench_press_multi_adj_incline', 'fit-place24:fp_eq_0287f92794a6'),
  ('rack_flat_bench_press_multi_adj_incline', 'fit-place24:fp_eq_0b7ade05c9c0'),
  ('rack_flat_bench_press_multi_flat_incline', 'fit-place24:fp_eq_0287f92794a6'),
  ('rack_flat_bench_press_multi_flat_incline', 'fit-place24:fp_eq_f03fe62567c5'),
  ('rack_flat_bench_press_multi_adjustable', 'fit-place24:fp_eq_0287f92794a6'),
  ('rack_flat_bench_press_multi_adjustable', 'fit-place24:fp_eq_c66a841e9ed5'),
  ('rack_flat_bench_press_multi_multi_decline', 'fit-place24:fp_eq_0287f92794a6'),
  ('rack_flat_bench_press_multi_multi_decline', 'fit-place24:fp_eq_538b557739d4'),
  ('rack_flat_bench_press_multi_multi_adj_decline', 'fit-place24:fp_eq_0287f92794a6'),
  ('rack_flat_bench_press_multi_multi_adj_decline', 'fit-place24:fp_eq_453fcb2d0cc8'),
  ('rack_flat_bench_press_multi_decline_flat', 'fit-place24:fp_eq_0287f92794a6'),
  ('rack_flat_bench_press_multi_decline_flat', 'fit-place24:fp_eq_57ab45d08062'),
  ('rack_flat_bench_press_multi_flat', 'fit-place24:fp_eq_0287f92794a6'),
  ('rack_flat_bench_press_multi_flat', 'fit-place24:fp_eq_3e928d59ac6c'),
  ('rack_flat_close_grip_bench_press_half_adj_incline', 'fit-place24:fp_eq_d45213d7da37'),
  ('rack_flat_close_grip_bench_press_half_adj_incline', 'fit-place24:fp_eq_0b7ade05c9c0'),
  ('rack_flat_close_grip_bench_press_half_flat_incline', 'fit-place24:fp_eq_d45213d7da37'),
  ('rack_flat_close_grip_bench_press_half_flat_incline', 'fit-place24:fp_eq_f03fe62567c5'),
  ('rack_flat_close_grip_bench_press_half_adjustable', 'fit-place24:fp_eq_d45213d7da37'),
  ('rack_flat_close_grip_bench_press_half_adjustable', 'fit-place24:fp_eq_c66a841e9ed5'),
  ('rack_flat_close_grip_bench_press_half_multi_decline', 'fit-place24:fp_eq_d45213d7da37'),
  ('rack_flat_close_grip_bench_press_half_multi_decline', 'fit-place24:fp_eq_538b557739d4'),
  ('rack_flat_close_grip_bench_press_half_multi_adj_decline', 'fit-place24:fp_eq_d45213d7da37'),
  ('rack_flat_close_grip_bench_press_half_multi_adj_decline', 'fit-place24:fp_eq_453fcb2d0cc8'),
  ('rack_flat_close_grip_bench_press_half_decline_flat', 'fit-place24:fp_eq_d45213d7da37'),
  ('rack_flat_close_grip_bench_press_half_decline_flat', 'fit-place24:fp_eq_57ab45d08062'),
  ('rack_flat_close_grip_bench_press_half_flat', 'fit-place24:fp_eq_d45213d7da37'),
  ('rack_flat_close_grip_bench_press_half_flat', 'fit-place24:fp_eq_3e928d59ac6c'),
  ('rack_flat_close_grip_bench_press_power_adj_incline', 'fit-place24:fp_eq_0b00220775cb'),
  ('rack_flat_close_grip_bench_press_power_adj_incline', 'fit-place24:fp_eq_0b7ade05c9c0'),
  ('rack_flat_close_grip_bench_press_power_flat_incline', 'fit-place24:fp_eq_0b00220775cb'),
  ('rack_flat_close_grip_bench_press_power_flat_incline', 'fit-place24:fp_eq_f03fe62567c5'),
  ('rack_flat_close_grip_bench_press_power_adjustable', 'fit-place24:fp_eq_0b00220775cb'),
  ('rack_flat_close_grip_bench_press_power_adjustable', 'fit-place24:fp_eq_c66a841e9ed5'),
  ('rack_flat_close_grip_bench_press_power_multi_decline', 'fit-place24:fp_eq_0b00220775cb'),
  ('rack_flat_close_grip_bench_press_power_multi_decline', 'fit-place24:fp_eq_538b557739d4'),
  ('rack_flat_close_grip_bench_press_power_multi_adj_decline', 'fit-place24:fp_eq_0b00220775cb'),
  ('rack_flat_close_grip_bench_press_power_multi_adj_decline', 'fit-place24:fp_eq_453fcb2d0cc8'),
  ('rack_flat_close_grip_bench_press_power_decline_flat', 'fit-place24:fp_eq_0b00220775cb'),
  ('rack_flat_close_grip_bench_press_power_decline_flat', 'fit-place24:fp_eq_57ab45d08062'),
  ('rack_flat_close_grip_bench_press_power_flat', 'fit-place24:fp_eq_0b00220775cb'),
  ('rack_flat_close_grip_bench_press_power_flat', 'fit-place24:fp_eq_3e928d59ac6c'),
  ('rack_flat_close_grip_bench_press_multi_adj_incline', 'fit-place24:fp_eq_0287f92794a6'),
  ('rack_flat_close_grip_bench_press_multi_adj_incline', 'fit-place24:fp_eq_0b7ade05c9c0'),
  ('rack_flat_close_grip_bench_press_multi_flat_incline', 'fit-place24:fp_eq_0287f92794a6'),
  ('rack_flat_close_grip_bench_press_multi_flat_incline', 'fit-place24:fp_eq_f03fe62567c5'),
  ('rack_flat_close_grip_bench_press_multi_adjustable', 'fit-place24:fp_eq_0287f92794a6'),
  ('rack_flat_close_grip_bench_press_multi_adjustable', 'fit-place24:fp_eq_c66a841e9ed5'),
  ('rack_flat_close_grip_bench_press_multi_multi_decline', 'fit-place24:fp_eq_0287f92794a6'),
  ('rack_flat_close_grip_bench_press_multi_multi_decline', 'fit-place24:fp_eq_538b557739d4'),
  ('rack_flat_close_grip_bench_press_multi_multi_adj_decline', 'fit-place24:fp_eq_0287f92794a6'),
  ('rack_flat_close_grip_bench_press_multi_multi_adj_decline', 'fit-place24:fp_eq_453fcb2d0cc8'),
  ('rack_flat_close_grip_bench_press_multi_decline_flat', 'fit-place24:fp_eq_0287f92794a6'),
  ('rack_flat_close_grip_bench_press_multi_decline_flat', 'fit-place24:fp_eq_57ab45d08062'),
  ('rack_flat_close_grip_bench_press_multi_flat', 'fit-place24:fp_eq_0287f92794a6'),
  ('rack_flat_close_grip_bench_press_multi_flat', 'fit-place24:fp_eq_3e928d59ac6c'),
  ('rack_flat_skull_crusher_half_adj_incline', 'fit-place24:fp_eq_d45213d7da37'),
  ('rack_flat_skull_crusher_half_adj_incline', 'fit-place24:fp_eq_0b7ade05c9c0'),
  ('rack_flat_skull_crusher_half_flat_incline', 'fit-place24:fp_eq_d45213d7da37'),
  ('rack_flat_skull_crusher_half_flat_incline', 'fit-place24:fp_eq_f03fe62567c5'),
  ('rack_flat_skull_crusher_half_adjustable', 'fit-place24:fp_eq_d45213d7da37'),
  ('rack_flat_skull_crusher_half_adjustable', 'fit-place24:fp_eq_c66a841e9ed5'),
  ('rack_flat_skull_crusher_half_multi_decline', 'fit-place24:fp_eq_d45213d7da37'),
  ('rack_flat_skull_crusher_half_multi_decline', 'fit-place24:fp_eq_538b557739d4'),
  ('rack_flat_skull_crusher_half_multi_adj_decline', 'fit-place24:fp_eq_d45213d7da37'),
  ('rack_flat_skull_crusher_half_multi_adj_decline', 'fit-place24:fp_eq_453fcb2d0cc8'),
  ('rack_flat_skull_crusher_half_decline_flat', 'fit-place24:fp_eq_d45213d7da37'),
  ('rack_flat_skull_crusher_half_decline_flat', 'fit-place24:fp_eq_57ab45d08062'),
  ('rack_flat_skull_crusher_half_flat', 'fit-place24:fp_eq_d45213d7da37'),
  ('rack_flat_skull_crusher_half_flat', 'fit-place24:fp_eq_3e928d59ac6c'),
  ('rack_flat_skull_crusher_power_adj_incline', 'fit-place24:fp_eq_0b00220775cb'),
  ('rack_flat_skull_crusher_power_adj_incline', 'fit-place24:fp_eq_0b7ade05c9c0'),
  ('rack_flat_skull_crusher_power_flat_incline', 'fit-place24:fp_eq_0b00220775cb'),
  ('rack_flat_skull_crusher_power_flat_incline', 'fit-place24:fp_eq_f03fe62567c5'),
  ('rack_flat_skull_crusher_power_adjustable', 'fit-place24:fp_eq_0b00220775cb'),
  ('rack_flat_skull_crusher_power_adjustable', 'fit-place24:fp_eq_c66a841e9ed5'),
  ('rack_flat_skull_crusher_power_multi_decline', 'fit-place24:fp_eq_0b00220775cb'),
  ('rack_flat_skull_crusher_power_multi_decline', 'fit-place24:fp_eq_538b557739d4'),
  ('rack_flat_skull_crusher_power_multi_adj_decline', 'fit-place24:fp_eq_0b00220775cb'),
  ('rack_flat_skull_crusher_power_multi_adj_decline', 'fit-place24:fp_eq_453fcb2d0cc8'),
  ('rack_flat_skull_crusher_power_decline_flat', 'fit-place24:fp_eq_0b00220775cb'),
  ('rack_flat_skull_crusher_power_decline_flat', 'fit-place24:fp_eq_57ab45d08062'),
  ('rack_flat_skull_crusher_power_flat', 'fit-place24:fp_eq_0b00220775cb'),
  ('rack_flat_skull_crusher_power_flat', 'fit-place24:fp_eq_3e928d59ac6c'),
  ('rack_flat_skull_crusher_multi_adj_incline', 'fit-place24:fp_eq_0287f92794a6'),
  ('rack_flat_skull_crusher_multi_adj_incline', 'fit-place24:fp_eq_0b7ade05c9c0'),
  ('rack_flat_skull_crusher_multi_flat_incline', 'fit-place24:fp_eq_0287f92794a6'),
  ('rack_flat_skull_crusher_multi_flat_incline', 'fit-place24:fp_eq_f03fe62567c5'),
  ('rack_flat_skull_crusher_multi_adjustable', 'fit-place24:fp_eq_0287f92794a6'),
  ('rack_flat_skull_crusher_multi_adjustable', 'fit-place24:fp_eq_c66a841e9ed5'),
  ('rack_flat_skull_crusher_multi_multi_decline', 'fit-place24:fp_eq_0287f92794a6'),
  ('rack_flat_skull_crusher_multi_multi_decline', 'fit-place24:fp_eq_538b557739d4'),
  ('rack_flat_skull_crusher_multi_multi_adj_decline', 'fit-place24:fp_eq_0287f92794a6'),
  ('rack_flat_skull_crusher_multi_multi_adj_decline', 'fit-place24:fp_eq_453fcb2d0cc8'),
  ('rack_flat_skull_crusher_multi_decline_flat', 'fit-place24:fp_eq_0287f92794a6'),
  ('rack_flat_skull_crusher_multi_decline_flat', 'fit-place24:fp_eq_57ab45d08062'),
  ('rack_flat_skull_crusher_multi_flat', 'fit-place24:fp_eq_0287f92794a6'),
  ('rack_flat_skull_crusher_multi_flat', 'fit-place24:fp_eq_3e928d59ac6c'),
  ('rack_flat_hip_thrust_half_adj_incline', 'fit-place24:fp_eq_d45213d7da37'),
  ('rack_flat_hip_thrust_half_adj_incline', 'fit-place24:fp_eq_0b7ade05c9c0'),
  ('rack_flat_hip_thrust_half_flat_incline', 'fit-place24:fp_eq_d45213d7da37'),
  ('rack_flat_hip_thrust_half_flat_incline', 'fit-place24:fp_eq_f03fe62567c5'),
  ('rack_flat_hip_thrust_half_adjustable', 'fit-place24:fp_eq_d45213d7da37'),
  ('rack_flat_hip_thrust_half_adjustable', 'fit-place24:fp_eq_c66a841e9ed5'),
  ('rack_flat_hip_thrust_half_multi_decline', 'fit-place24:fp_eq_d45213d7da37'),
  ('rack_flat_hip_thrust_half_multi_decline', 'fit-place24:fp_eq_538b557739d4'),
  ('rack_flat_hip_thrust_half_multi_adj_decline', 'fit-place24:fp_eq_d45213d7da37'),
  ('rack_flat_hip_thrust_half_multi_adj_decline', 'fit-place24:fp_eq_453fcb2d0cc8'),
  ('rack_flat_hip_thrust_half_decline_flat', 'fit-place24:fp_eq_d45213d7da37'),
  ('rack_flat_hip_thrust_half_decline_flat', 'fit-place24:fp_eq_57ab45d08062'),
  ('rack_flat_hip_thrust_half_flat', 'fit-place24:fp_eq_d45213d7da37'),
  ('rack_flat_hip_thrust_half_flat', 'fit-place24:fp_eq_3e928d59ac6c'),
  ('rack_flat_hip_thrust_power_adj_incline', 'fit-place24:fp_eq_0b00220775cb'),
  ('rack_flat_hip_thrust_power_adj_incline', 'fit-place24:fp_eq_0b7ade05c9c0'),
  ('rack_flat_hip_thrust_power_flat_incline', 'fit-place24:fp_eq_0b00220775cb'),
  ('rack_flat_hip_thrust_power_flat_incline', 'fit-place24:fp_eq_f03fe62567c5'),
  ('rack_flat_hip_thrust_power_adjustable', 'fit-place24:fp_eq_0b00220775cb'),
  ('rack_flat_hip_thrust_power_adjustable', 'fit-place24:fp_eq_c66a841e9ed5'),
  ('rack_flat_hip_thrust_power_multi_decline', 'fit-place24:fp_eq_0b00220775cb'),
  ('rack_flat_hip_thrust_power_multi_decline', 'fit-place24:fp_eq_538b557739d4'),
  ('rack_flat_hip_thrust_power_multi_adj_decline', 'fit-place24:fp_eq_0b00220775cb'),
  ('rack_flat_hip_thrust_power_multi_adj_decline', 'fit-place24:fp_eq_453fcb2d0cc8'),
  ('rack_flat_hip_thrust_power_decline_flat', 'fit-place24:fp_eq_0b00220775cb'),
  ('rack_flat_hip_thrust_power_decline_flat', 'fit-place24:fp_eq_57ab45d08062'),
  ('rack_flat_hip_thrust_power_flat', 'fit-place24:fp_eq_0b00220775cb'),
  ('rack_flat_hip_thrust_power_flat', 'fit-place24:fp_eq_3e928d59ac6c'),
  ('rack_flat_hip_thrust_multi_adj_incline', 'fit-place24:fp_eq_0287f92794a6'),
  ('rack_flat_hip_thrust_multi_adj_incline', 'fit-place24:fp_eq_0b7ade05c9c0'),
  ('rack_flat_hip_thrust_multi_flat_incline', 'fit-place24:fp_eq_0287f92794a6'),
  ('rack_flat_hip_thrust_multi_flat_incline', 'fit-place24:fp_eq_f03fe62567c5'),
  ('rack_flat_hip_thrust_multi_adjustable', 'fit-place24:fp_eq_0287f92794a6'),
  ('rack_flat_hip_thrust_multi_adjustable', 'fit-place24:fp_eq_c66a841e9ed5'),
  ('rack_flat_hip_thrust_multi_multi_decline', 'fit-place24:fp_eq_0287f92794a6'),
  ('rack_flat_hip_thrust_multi_multi_decline', 'fit-place24:fp_eq_538b557739d4'),
  ('rack_flat_hip_thrust_multi_multi_adj_decline', 'fit-place24:fp_eq_0287f92794a6'),
  ('rack_flat_hip_thrust_multi_multi_adj_decline', 'fit-place24:fp_eq_453fcb2d0cc8'),
  ('rack_flat_hip_thrust_multi_decline_flat', 'fit-place24:fp_eq_0287f92794a6'),
  ('rack_flat_hip_thrust_multi_decline_flat', 'fit-place24:fp_eq_57ab45d08062'),
  ('rack_flat_hip_thrust_multi_flat', 'fit-place24:fp_eq_0287f92794a6'),
  ('rack_flat_hip_thrust_multi_flat', 'fit-place24:fp_eq_3e928d59ac6c'),
  ('rack_incline_incline_barbell_press_half_adj_incline', 'fit-place24:fp_eq_d45213d7da37'),
  ('rack_incline_incline_barbell_press_half_adj_incline', 'fit-place24:fp_eq_0b7ade05c9c0'),
  ('rack_incline_incline_barbell_press_half_flat_incline', 'fit-place24:fp_eq_d45213d7da37'),
  ('rack_incline_incline_barbell_press_half_flat_incline', 'fit-place24:fp_eq_f03fe62567c5'),
  ('rack_incline_incline_barbell_press_half_adjustable', 'fit-place24:fp_eq_d45213d7da37'),
  ('rack_incline_incline_barbell_press_half_adjustable', 'fit-place24:fp_eq_c66a841e9ed5'),
  ('rack_incline_incline_barbell_press_power_adj_incline', 'fit-place24:fp_eq_0b00220775cb'),
  ('rack_incline_incline_barbell_press_power_adj_incline', 'fit-place24:fp_eq_0b7ade05c9c0'),
  ('rack_incline_incline_barbell_press_power_flat_incline', 'fit-place24:fp_eq_0b00220775cb'),
  ('rack_incline_incline_barbell_press_power_flat_incline', 'fit-place24:fp_eq_f03fe62567c5'),
  ('rack_incline_incline_barbell_press_power_adjustable', 'fit-place24:fp_eq_0b00220775cb'),
  ('rack_incline_incline_barbell_press_power_adjustable', 'fit-place24:fp_eq_c66a841e9ed5'),
  ('rack_incline_incline_barbell_press_multi_adj_incline', 'fit-place24:fp_eq_0287f92794a6'),
  ('rack_incline_incline_barbell_press_multi_adj_incline', 'fit-place24:fp_eq_0b7ade05c9c0'),
  ('rack_incline_incline_barbell_press_multi_flat_incline', 'fit-place24:fp_eq_0287f92794a6'),
  ('rack_incline_incline_barbell_press_multi_flat_incline', 'fit-place24:fp_eq_f03fe62567c5'),
  ('rack_incline_incline_barbell_press_multi_adjustable', 'fit-place24:fp_eq_0287f92794a6'),
  ('rack_incline_incline_barbell_press_multi_adjustable', 'fit-place24:fp_eq_c66a841e9ed5'),
  ('rack_decline_decline_barbell_press_half_multi_decline', 'fit-place24:fp_eq_d45213d7da37'),
  ('rack_decline_decline_barbell_press_half_multi_decline', 'fit-place24:fp_eq_538b557739d4'),
  ('rack_decline_decline_barbell_press_half_multi_adj_decline', 'fit-place24:fp_eq_d45213d7da37'),
  ('rack_decline_decline_barbell_press_half_multi_adj_decline', 'fit-place24:fp_eq_453fcb2d0cc8'),
  ('rack_decline_decline_barbell_press_half_decline_flat', 'fit-place24:fp_eq_d45213d7da37'),
  ('rack_decline_decline_barbell_press_half_decline_flat', 'fit-place24:fp_eq_57ab45d08062'),
  ('rack_decline_decline_barbell_press_power_multi_decline', 'fit-place24:fp_eq_0b00220775cb'),
  ('rack_decline_decline_barbell_press_power_multi_decline', 'fit-place24:fp_eq_538b557739d4'),
  ('rack_decline_decline_barbell_press_power_multi_adj_decline', 'fit-place24:fp_eq_0b00220775cb'),
  ('rack_decline_decline_barbell_press_power_multi_adj_decline', 'fit-place24:fp_eq_453fcb2d0cc8'),
  ('rack_decline_decline_barbell_press_power_decline_flat', 'fit-place24:fp_eq_0b00220775cb'),
  ('rack_decline_decline_barbell_press_power_decline_flat', 'fit-place24:fp_eq_57ab45d08062'),
  ('rack_decline_decline_barbell_press_multi_multi_decline', 'fit-place24:fp_eq_0287f92794a6'),
  ('rack_decline_decline_barbell_press_multi_multi_decline', 'fit-place24:fp_eq_538b557739d4'),
  ('rack_decline_decline_barbell_press_multi_multi_adj_decline', 'fit-place24:fp_eq_0287f92794a6'),
  ('rack_decline_decline_barbell_press_multi_multi_adj_decline', 'fit-place24:fp_eq_453fcb2d0cc8'),
  ('rack_decline_decline_barbell_press_multi_decline_flat', 'fit-place24:fp_eq_0287f92794a6'),
  ('rack_decline_decline_barbell_press_multi_decline_flat', 'fit-place24:fp_eq_57ab45d08062'),
  ('dumbbell_flat_flat_dumbbell_press_db_adj_incline', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_flat_flat_dumbbell_press_db_adj_incline', 'fit-place24:fp_eq_0b7ade05c9c0'),
  ('dumbbell_flat_flat_dumbbell_press_db_flat_incline', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_flat_flat_dumbbell_press_db_flat_incline', 'fit-place24:fp_eq_f03fe62567c5'),
  ('dumbbell_flat_flat_dumbbell_press_db_adjustable', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_flat_flat_dumbbell_press_db_adjustable', 'fit-place24:fp_eq_c66a841e9ed5'),
  ('dumbbell_flat_flat_dumbbell_press_db_multi_decline', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_flat_flat_dumbbell_press_db_multi_decline', 'fit-place24:fp_eq_538b557739d4'),
  ('dumbbell_flat_flat_dumbbell_press_db_multi_adj_decline', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_flat_flat_dumbbell_press_db_multi_adj_decline', 'fit-place24:fp_eq_453fcb2d0cc8'),
  ('dumbbell_flat_flat_dumbbell_press_db_decline_flat', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_flat_flat_dumbbell_press_db_decline_flat', 'fit-place24:fp_eq_57ab45d08062'),
  ('dumbbell_flat_flat_dumbbell_press_db_flat', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_flat_flat_dumbbell_press_db_flat', 'fit-place24:fp_eq_3e928d59ac6c'),
  ('dumbbell_flat_dumbbell_fly_db_adj_incline', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_flat_dumbbell_fly_db_adj_incline', 'fit-place24:fp_eq_0b7ade05c9c0'),
  ('dumbbell_flat_dumbbell_fly_db_flat_incline', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_flat_dumbbell_fly_db_flat_incline', 'fit-place24:fp_eq_f03fe62567c5'),
  ('dumbbell_flat_dumbbell_fly_db_adjustable', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_flat_dumbbell_fly_db_adjustable', 'fit-place24:fp_eq_c66a841e9ed5'),
  ('dumbbell_flat_dumbbell_fly_db_multi_decline', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_flat_dumbbell_fly_db_multi_decline', 'fit-place24:fp_eq_538b557739d4'),
  ('dumbbell_flat_dumbbell_fly_db_multi_adj_decline', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_flat_dumbbell_fly_db_multi_adj_decline', 'fit-place24:fp_eq_453fcb2d0cc8'),
  ('dumbbell_flat_dumbbell_fly_db_decline_flat', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_flat_dumbbell_fly_db_decline_flat', 'fit-place24:fp_eq_57ab45d08062'),
  ('dumbbell_flat_dumbbell_fly_db_flat', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_flat_dumbbell_fly_db_flat', 'fit-place24:fp_eq_3e928d59ac6c'),
  ('dumbbell_flat_dumbbell_pullover_db_adj_incline', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_flat_dumbbell_pullover_db_adj_incline', 'fit-place24:fp_eq_0b7ade05c9c0'),
  ('dumbbell_flat_dumbbell_pullover_db_flat_incline', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_flat_dumbbell_pullover_db_flat_incline', 'fit-place24:fp_eq_f03fe62567c5'),
  ('dumbbell_flat_dumbbell_pullover_db_adjustable', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_flat_dumbbell_pullover_db_adjustable', 'fit-place24:fp_eq_c66a841e9ed5'),
  ('dumbbell_flat_dumbbell_pullover_db_multi_decline', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_flat_dumbbell_pullover_db_multi_decline', 'fit-place24:fp_eq_538b557739d4'),
  ('dumbbell_flat_dumbbell_pullover_db_multi_adj_decline', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_flat_dumbbell_pullover_db_multi_adj_decline', 'fit-place24:fp_eq_453fcb2d0cc8'),
  ('dumbbell_flat_dumbbell_pullover_db_decline_flat', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_flat_dumbbell_pullover_db_decline_flat', 'fit-place24:fp_eq_57ab45d08062'),
  ('dumbbell_flat_dumbbell_pullover_db_flat', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_flat_dumbbell_pullover_db_flat', 'fit-place24:fp_eq_3e928d59ac6c'),
  ('dumbbell_flat_bulgarian_split_squat_db_adj_incline', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_flat_bulgarian_split_squat_db_adj_incline', 'fit-place24:fp_eq_0b7ade05c9c0'),
  ('dumbbell_flat_bulgarian_split_squat_db_flat_incline', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_flat_bulgarian_split_squat_db_flat_incline', 'fit-place24:fp_eq_f03fe62567c5'),
  ('dumbbell_flat_bulgarian_split_squat_db_adjustable', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_flat_bulgarian_split_squat_db_adjustable', 'fit-place24:fp_eq_c66a841e9ed5'),
  ('dumbbell_flat_bulgarian_split_squat_db_multi_decline', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_flat_bulgarian_split_squat_db_multi_decline', 'fit-place24:fp_eq_538b557739d4'),
  ('dumbbell_flat_bulgarian_split_squat_db_multi_adj_decline', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_flat_bulgarian_split_squat_db_multi_adj_decline', 'fit-place24:fp_eq_453fcb2d0cc8'),
  ('dumbbell_flat_bulgarian_split_squat_db_decline_flat', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_flat_bulgarian_split_squat_db_decline_flat', 'fit-place24:fp_eq_57ab45d08062'),
  ('dumbbell_flat_bulgarian_split_squat_db_flat', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_flat_bulgarian_split_squat_db_flat', 'fit-place24:fp_eq_3e928d59ac6c'),
  ('dumbbell_incline_incline_dumbbell_press_db_adj_incline', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_incline_incline_dumbbell_press_db_adj_incline', 'fit-place24:fp_eq_0b7ade05c9c0'),
  ('dumbbell_incline_incline_dumbbell_press_db_flat_incline', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_incline_incline_dumbbell_press_db_flat_incline', 'fit-place24:fp_eq_f03fe62567c5'),
  ('dumbbell_incline_incline_dumbbell_press_db_adjustable', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_incline_incline_dumbbell_press_db_adjustable', 'fit-place24:fp_eq_c66a841e9ed5'),
  ('dumbbell_incline_incline_dumbbell_fly_db_adj_incline', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_incline_incline_dumbbell_fly_db_adj_incline', 'fit-place24:fp_eq_0b7ade05c9c0'),
  ('dumbbell_incline_incline_dumbbell_fly_db_flat_incline', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_incline_incline_dumbbell_fly_db_flat_incline', 'fit-place24:fp_eq_f03fe62567c5'),
  ('dumbbell_incline_incline_dumbbell_fly_db_adjustable', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_incline_incline_dumbbell_fly_db_adjustable', 'fit-place24:fp_eq_c66a841e9ed5'),
  ('dumbbell_incline_chest_supported_dumbbell_row_db_adj_incline', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_incline_chest_supported_dumbbell_row_db_adj_incline', 'fit-place24:fp_eq_0b7ade05c9c0'),
  ('dumbbell_incline_chest_supported_dumbbell_row_db_flat_incline', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_incline_chest_supported_dumbbell_row_db_flat_incline', 'fit-place24:fp_eq_f03fe62567c5'),
  ('dumbbell_incline_chest_supported_dumbbell_row_db_adjustable', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_incline_chest_supported_dumbbell_row_db_adjustable', 'fit-place24:fp_eq_c66a841e9ed5'),
  ('dumbbell_incline_incline_dumbbell_curl_db_adj_incline', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_incline_incline_dumbbell_curl_db_adj_incline', 'fit-place24:fp_eq_0b7ade05c9c0'),
  ('dumbbell_incline_incline_dumbbell_curl_db_flat_incline', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_incline_incline_dumbbell_curl_db_flat_incline', 'fit-place24:fp_eq_f03fe62567c5'),
  ('dumbbell_incline_incline_dumbbell_curl_db_adjustable', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_incline_incline_dumbbell_curl_db_adjustable', 'fit-place24:fp_eq_c66a841e9ed5'),
  ('dumbbell_incline_spider_curl_db_adj_incline', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_incline_spider_curl_db_adj_incline', 'fit-place24:fp_eq_0b7ade05c9c0'),
  ('dumbbell_incline_spider_curl_db_flat_incline', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_incline_spider_curl_db_flat_incline', 'fit-place24:fp_eq_f03fe62567c5'),
  ('dumbbell_incline_spider_curl_db_adjustable', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_incline_spider_curl_db_adjustable', 'fit-place24:fp_eq_c66a841e9ed5'),
  ('dumbbell_decline_decline_dumbbell_press_db_multi_decline', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_decline_decline_dumbbell_press_db_multi_decline', 'fit-place24:fp_eq_538b557739d4'),
  ('dumbbell_decline_decline_dumbbell_press_db_multi_adj_decline', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_decline_decline_dumbbell_press_db_multi_adj_decline', 'fit-place24:fp_eq_453fcb2d0cc8'),
  ('dumbbell_decline_decline_dumbbell_press_db_decline_flat', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_decline_decline_dumbbell_press_db_decline_flat', 'fit-place24:fp_eq_57ab45d08062'),
  ('dumbbell_decline_decline_dumbbell_fly_db_multi_decline', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_decline_decline_dumbbell_fly_db_multi_decline', 'fit-place24:fp_eq_538b557739d4'),
  ('dumbbell_decline_decline_dumbbell_fly_db_multi_adj_decline', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_decline_decline_dumbbell_fly_db_multi_adj_decline', 'fit-place24:fp_eq_453fcb2d0cc8'),
  ('dumbbell_decline_decline_dumbbell_fly_db_decline_flat', 'fit-place24:fp_eq_693fa2dd0404'),
  ('dumbbell_decline_decline_dumbbell_fly_db_decline_flat', 'fit-place24:fp_eq_57ab45d08062'),
  ('preacher_db_preacher_curl_db_adj_arm', 'fit-place24:fp_eq_693fa2dd0404'),
  ('preacher_db_preacher_curl_db_adj_arm', 'fit-place24:fp_eq_999e7b88bccd'),
  ('preacher_db_preacher_curl_db_arm', 'fit-place24:fp_eq_693fa2dd0404'),
  ('preacher_db_preacher_curl_db_arm', 'fit-place24:fp_eq_5354722256ab'),
  ('preacher_db_preacher_curl_db_curl', 'fit-place24:fp_eq_693fa2dd0404'),
  ('preacher_db_preacher_curl_db_curl', 'fit-place24:fp_eq_53beebd50e63'),
  ('preacher_rack_preacher_curl_half_adj_arm', 'fit-place24:fp_eq_d45213d7da37'),
  ('preacher_rack_preacher_curl_half_adj_arm', 'fit-place24:fp_eq_999e7b88bccd'),
  ('preacher_rack_preacher_curl_half_arm', 'fit-place24:fp_eq_d45213d7da37'),
  ('preacher_rack_preacher_curl_half_arm', 'fit-place24:fp_eq_5354722256ab'),
  ('preacher_rack_preacher_curl_half_curl', 'fit-place24:fp_eq_d45213d7da37'),
  ('preacher_rack_preacher_curl_half_curl', 'fit-place24:fp_eq_53beebd50e63'),
  ('preacher_rack_preacher_curl_power_adj_arm', 'fit-place24:fp_eq_0b00220775cb'),
  ('preacher_rack_preacher_curl_power_adj_arm', 'fit-place24:fp_eq_999e7b88bccd'),
  ('preacher_rack_preacher_curl_power_arm', 'fit-place24:fp_eq_0b00220775cb'),
  ('preacher_rack_preacher_curl_power_arm', 'fit-place24:fp_eq_5354722256ab'),
  ('preacher_rack_preacher_curl_power_curl', 'fit-place24:fp_eq_0b00220775cb'),
  ('preacher_rack_preacher_curl_power_curl', 'fit-place24:fp_eq_53beebd50e63'),
  ('preacher_rack_preacher_curl_multi_adj_arm', 'fit-place24:fp_eq_0287f92794a6'),
  ('preacher_rack_preacher_curl_multi_adj_arm', 'fit-place24:fp_eq_999e7b88bccd'),
  ('preacher_rack_preacher_curl_multi_arm', 'fit-place24:fp_eq_0287f92794a6'),
  ('preacher_rack_preacher_curl_multi_arm', 'fit-place24:fp_eq_5354722256ab'),
  ('preacher_rack_preacher_curl_multi_curl', 'fit-place24:fp_eq_0287f92794a6'),
  ('preacher_rack_preacher_curl_multi_curl', 'fit-place24:fp_eq_53beebd50e63')
on conflict (rule_id, equipment_id) do nothing;

create or replace function public.gym_store_exercise_ids(target_store_id text)
returns table(exercise_id text)
language sql
stable
security invoker
set search_path = public
as $$
  with available_equipment as (
    select gse.equipment_id
    from public.gym_store_equipment gse
    where gse.store_id = target_store_id
      and gse.available = true
  ),
  direct_exercises as (
    select distinct eem.exercise_id
    from available_equipment a
    join public.equipment_exercise_mapping eem
      on eem.equipment_id = a.equipment_id
  ),
  satisfied_rules as (
    select r.exercise_id
    from public.exercise_equipment_rules r
    join public.exercise_equipment_rule_items ri
      on ri.rule_id = r.id
    left join available_equipment a
      on a.equipment_id = ri.equipment_id
    group by r.id, r.exercise_id
    having count(*) = count(a.equipment_id)
  )
  select d.exercise_id from direct_exercises d
  union
  select s.exercise_id from satisfied_rules s;
$$;

revoke all on function public.gym_store_exercise_ids(text) from public;
grant execute on function public.gym_store_exercise_ids(text) to anon, authenticated;

commit;
